# -*- coding: utf-8 -*-
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##      http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## Author: Richard Sproat (rws@xoba.com)

"""Defines the set of concepts, linking them to plausible graphical forms.
"""

CONCEPTS = {
  '@PERSON' : '⚥',
  '@MAN' : '♂',
  '@WOMAN' : '♀',
  '@HOUSE' : '☖',
  '@BRONZE' : '▰',
  '@GOLD' : 'ꃑ',
  '@SILVER' : 'ꂢ',
  '@SWORD' : '⚔',
  '@MEAT' : '☣',
  '@SHEEP' : '♈',
  '@OX' : '♉',
  '@GOAT' : '♑',
  '@FISH' : 'ꈊ',
  '@TREE' : 'ꈔ',
  '@BARLEY' : 'ꆡ',
  '@WHEAT' : 'ꎺ',
  '@WATER' : '♒',
  '@STONE' : '░',
  '@CLOTHING' : 'ꆘ',
  '@FIELD' : 'ꐚ',
  '@TEMPLE' : '▟',
  '@GOD' : '☸',
  '@AXE' : '⁋',
  '@SCYTHE' : '☭',
  '@DOG' : 'ꀳ',
  '@LION' : '♌',
  '@WOLF' : 'ꉴ',
  '@DEMON' : '☿',
  '@SNAKE' : '⚕',
  '@TURTLE' : 'ꉸ',
  '@FRUIT' : '☌',
  '@HILL' : '☶',
  '@CAVE' : '◠',
  '@TOWN' : '♖',
  '@ENCLOSURE' : '☐',
  '@FLOWER' : '⚜',
  '@RAIN' : '☔',
  '@THUNDER' : '⚡',
  '@CLOUD' : '☁',
  '@SUN' : '☉',
  '@MOON' : '☽',
  '@HEART' : '♡',
  '@LUNG' : '♺',
  '@LEG' : '⼅',
  '@ARM' : 'ꁳ',
  '@FINGER' : '☚',
  '@HEAD' : '☺',
  '@TONGUE' : 'ꇩ',
  '@EYE' : '◎',
  '@EAR' : 'ꎙ',
  '@NOSE' : 'ꎔ',
  '@GUTS' : '♽',
  '@PENIS' : 'ꅏ',
  '@VAGINA' : '⚏',
  '@HAIR' : 'ꊤ',
  '@SKIN' : 'ꁸ',
  '@SHELL' : 'ꌋ',
  '@BONE' : 'ꀷ',
  '@BLOOD' : 'ꋓ',
  '@LIVER' : '❦',
  '@FARM' : 'ꌆ',
  '@LOCUST' : 'ꋸ',
  '@STICK' : '▕',
  '@STAR' : '☆',
  '@EARTH' : '☷',
  '@ASS' : '♘',
  '@DEATH' : '☠',
  '@BIRTH' : '〄',
  '@WOMB' : '☤',
  '@MILK' : 'ꎍ',
  '@COAL' : '■',
  '@SEED' : 'ꄍ',
  '@LEAF' : '☘',
  '@CHILD' : 'ꐕ',
  '@ANTELOPE' : 'ꎢ',
  '@BEAR' : 'ꄕ',
  '@BEE' : 'ꎁ',
  '@MOUSE' : 'ꎃ',
  '@DUNG' : '♨',
  '@PLOUGH' : '♠',
  '@SPROUT' : '♧',
  '@ICE' : '⼎',
  '@DAY' : '☀',
  '@NIGHT' : '☾',
  '@WINTER' : '☃',
  '@SUMMER' : '☼',
  '@AUTUMN' : 'ꏃ',
  '@SPRING' : 'ꐳ',
  '@KING' : '♔',
  '@GOOSE' : 'ꎉ',
  '@PRIEST' : '♗',
  '@ROAD' : '⚌',
  '@CART' : 'ꌴ',
  '@GRASS' : 'ꍓ',
  '@FIRE' : '☲',
  '@WIND' : '☴',
  '@NAIL' : '丁',
  '@BREAST' : '⚆',
  '@BOWL' : '◡',
  '@CUP' : '☕',}

NUM_CONCEPTS = len(CONCEPTS)
